name: FarmerPlus
version: 1.0.0
main: me.kafein.farmer.bukkit.loader.BukkitPluginLoader
api-version: 1.13
authors: [ Kafein ]
description: Farmer plugin for SkyBlock servers.
depend: [Vault]
softdepend: [ASkyBlock]